(ns euler.solutions.029
  "How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?"
  (:require [clojure.math.numeric-tower :refer [expt ]]) )

(def terms
  (set
    (for [a (range 2 101)
          b (range 2 101)]
      (expt a b)) ))

(->> terms
     (count)
     (println "Solution 029:")
     (time))
